---
name: Martín
surname: Venegas M.
position: "Estudiante Sociología - Nudesoc researcher"
address: "Facultad de Ciencias Sociales, Universidad de Chile"
phone: +569 84791222
email: "martin.venegas@ug.uchile.cl"
github: Martin-Venegas-M
date: "`r format(Sys.time(), '%B %Y')`"
aboutme: jasfjashjfhsajhfjashjfhasjhfjas
output: vitae::moderncv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Resumen

Actualmente estudiante de cuarto año en Sociología

# Estudios

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Lienciatura en Sociología", "2017-actual", "Universidad de Chile", "Santiago, Chile",
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Experiencia laboral y académica

```{r}
library(tibble)
tribble(
  ~ Role, ~ Year, ~ Institution, ~ Where, ~ Details,
  "Co-Investigador Pasante", "2020-actual", "Fundación Todo Mejora", "Santiago, Chile", "Encargado de co-liderar el
desarrollo de investigación sobre la intervención Hora Segura y sus usuarios/as, a partir de
metodología cualitativa y/o mixta.",

"Ayudante de la catedra Estadística Multivariada", "2020-actual", "Facultad de Ciencias Sociales, Universidad de Chile", "Santiago, Chile", "Apoyo y asesorías a estudiantes de tercer año de la carrera de Sociología respecto a técnicas de análisis multivariado y desarrollo de investigación académica cuantitativa",

"Investigador", "2019-actual", "Nucleo de Sociología Contingente (NUDESOC)", "Santiago, Chile", "Desarrollo de investigaciones en temáticas contingentes, especialmente acción colectiva, movimientos sociales y política",

"Tutor de Apoyo al Aprendizaje - LEA", "2019-actual", "Centro IDEA, Facultad de Ciencias Sociales, Universidad de Chile", "Santiago, Chile", "Acompañamiento y orientación en estrategias de estudio y contenidos de cátedra para estudiantes de la carrera de Sociología",

"Ayudante de la catedra Estrategias de Investigación Cuantitativa", "2019", "Facultad de Ciencias Sociales, Universidad de Chile", "Santiago, Chile", "Apoyo y asesoría a estudiantes segundo año de la carrera de Sociología respecto a métodología cuantitativa, especialmente en lo referido a construcción de herramientas, levantamiento de datos, analisis de datos etc",

"Encuestador", "2018", "Semsum Consultora", "Santiago, Chile", "Aplicación de cuestionario para levantamiento de información respecto a opiniones en torno a la Municipalidad de Lampa",

"Transcriptor", "2017", "Conexium Consultoría y Cía. Ltda.", "Santiago, Chile", "Encargado de transcribir entrevistas en profundidad y grupos focales para proyecto de investigación"
) %>% 
  detailed_entries(Role, Year, Institution, Where, Details)
```


