---
title: "Principales motivaciones y habilidades"
author: "Martín Venegas"
date: "9/9/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Mis principales motivaciones por trabajar en este proyecto se dividen en tres dimensiones. En primer lugar, considero que los requerimientos y tareas del proyecto se ajustan a mis intereses en el área cuantitativa y a la trayectoria que he venido armando a través de los cursos en la universidad, y que me gustaría consolidar. En segundo lugar, el tema del proyecto toca ciertas aristas en los que aspiro a desempeñarme en un futuro cercano, especialmente en lo relacionado a participación y socialización política, tematicas las cuales desde el 18 de Octubre han acaparado mi especial interés. En tercer lugar, creo que el trabajar en un proyecto Fondecyt es una instancia sumamente rica de aprendizaje y un desafio que me permitiría desarrollarme profesionalmente.

Por otro lado, considero estar capacitado para el cargo en tanto a lo largo de mi trayectoria universitaria he desarrollado un método de trabajo caracterizado por la buena planificación de tareas y tiempos, responsabilidad, transparencia, coordinación y trabajo en equipo. Así también, considero poder aportar con una serie de habilidades que he ido adquiriendo y desarrollando tanto en cursos de la universidad como en distintas experiencias académicas y laborales, especialmente en lo que refiere a construcción de instrumentos, procesamiento y análisis de datos, uso de técnicas uni, bi y multivariadas (p.ej regresiones, análisis multinivel), elaboración de productos académicos y comunicación de resultados. Además, cuento con el dominio de una serie de herramientas afines como R/RStudio, Git/Github, Mendeley/Zotero, etc.

En suma, trabajar en este proyecto sería una muy grata experiencia en la que ambas partes se vean beneficiadas y que, además, se presenta un momento oportuno de mi trayectoria universitaria en tanto cuento con gran disponibilidad de tiempo en el periodo que se enmarca el desarrollo del proyecto.